Repository numericalEFT/FeynmanDiagram.jl, pull requests merged in 2022-12, with the labels that each got.

#67 Remove extra factor of xi in susceptibility
  docs/src/assets/diagrams/susceptibility.pdf
  docs/src/assets/diagrams/susceptibility.svg
  docs/src/assets/diagrams/susceptibility.tex
  docs/src/manual/feynman_rule.md
  src/diagram_tree/io.jl
Labels: documentation

#68 build diagram from vertices
  src/FeynmanDiagram.jl
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/common.jl
  src/computational_graph/graph.jl
  src/computational_graph/graph_dev.jl
  src/computational_graph/io.jl
  test/ComputationalGraph.jl
  test/runtests.jl
Labels: enhancement

#70 refactor
  src/FeynmanDiagram.jl
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/common.jl
  src/computational_graph/diagram_v0.jl
  src/computational_graph/graph.jl
  src/quantum_operator/QuantumOperators.jl
  src/quantum_operator/expression.jl
  src/quantum_operator/operator.jl
  test/ComputationalGraph.jl
Labels: enhancement

#72 Test updated pathing for deployed docpages
  .gitignore
  docs/src/manual/feynman_rule.md
Labels: bug, documentation

#76 Computgraph kun
  src/FeynmanDiagram.jl
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/common.jl
  src/computational_graph/graph.jl
  src/computational_graph/io.jl
  src/computational_graph/tree.jl
  test/computational_graph.jl
Labels: enhancement

#78 compiler for static_graph
  src/FeynmanDiagram.jl
  src/backend/compiler.jl
  src/backend/static.jl
  test/compiler.jl
Labels: enhancement

#79 change external convention
  src/FeynmanDiagram.jl
  src/backend/compiler.jl
  src/backend/static.jl
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/graph.jl
  src/frontend/frontends.jl
  src/frontend/parquet.jl
  src/quantum_operator/expression.jl
  test/compiler.jl
  test/computational_graph.jl
Labels: enhancement

#84 Refactor & fix subgraph factors
  src/computational_graph/common.jl
  src/computational_graph/deprecated.jl
  src/computational_graph/graph.jl
  src/computational_graph/io.jl
  test/computational_graph.jl
  test/deprecated.jl
Labels: bug, refactor

#90 remove redundent constructor
  src/quantum_operator/operator.jl
  test/quantum_operator.jl
Labels: enhancement

#91 refactor topology and constructor of Graph
  src/FeynmanDiagram.jl
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/graph.jl
  test/computational_graph.jl
Labels: enhancement

#92 implement Daniel's idea
  src/FeynmanDiagram.jl
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/graph.jl
  src/quantum_operator/QuantumOperators.jl
  src/quantum_operator/expression.jl
  test/computational_graph.jl
Labels: enhancement

#94 Computgraph xc
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/transform.jl
  test/computational_graph.jl
Labels: enhancement

#95 implement three bubble diagrams
  src/FeynmanDiagram.jl
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/graph.jl
  src/frontend/frontends.jl
  src/frontend/parquet.jl
  src/quantum_operator/operator.jl
Labels: enhancement

#100 implement GraphVector
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/graphvector.jl
  test/computational_graph.jl
Labels: enhancement

#103 Bugfix
  src/computational_graph/graph.jl
  test/computational_graph.jl
Labels: bug

#104 Computgraph kun
  .gitignore
  Project.toml
  docs/make.jl
  docs/src/index.md
  docs/src/lib/computgraph.md
  docs/src/lib/operator.md
  docs/src/manual/feynman_rule.md
  example/generatedfunction.jl
  src/FeynmanDiagram.jl
  src/backend/compiler.jl
  src/backend/static.jl
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/GreenDiagram.jl
  src/computational_graph/common.jl
  src/computational_graph/deprecated.jl
  src/computational_graph/graph.jl
  src/computational_graph/graphvector.jl
  src/computational_graph/io.jl
  src/computational_graph/operation.jl
  src/computational_graph/transform.jl
  src/computational_graph/tree.jl
  src/diagram_tree/DiagTree.jl
  src/diagram_tree/optimize.jl
  src/expression_tree/ExpressionTree.jl
  src/expression_tree/build.jl
  src/expression_tree/eval.jl
  src/expression_tree/pool.jl
  src/expression_tree/tree.jl
  src/frontend/frontends.jl
  src/frontend/parquet.jl
  src/parquet_builder/common.jl
  src/parquet_builder/parquet.jl
  src/parquet_builder/vertex3.jl
  src/quantum_operator/QuantumOperators.jl
  src/quantum_operator/expression.jl
  src/quantum_operator/operator.jl
  test/benchmark.jl
  test/compiler.jl
  test/computational_graph.jl
  test/deprecated.jl
  test/quantum_operator.jl
  test/runtests.jl
Labels: enhancement

#83 factorize work in progress
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/graph.jl
  src/computational_graph/io.jl
  test/computational_graph.jl
Labels: enhancement
