Repository numericalEFT/FeynmanDiagram.jl, pull requests merged in 2023-09, with the labels that each got.

#130 Tao ad
  Project.toml
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/eval.jl
  src/computational_graph/graph.jl
  src/computational_graph/operation.jl
  src/computational_graph/tree_properties.jl
  test/computational_graph.jl
Labels: enhancement

#132 Computgraph daniel
  src/FeynmanDiagram.jl
  src/backend/compiler.jl
  src/backend/static.jl
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/abstractgraph.jl
  src/computational_graph/feynmangraph.jl
  src/computational_graph/graph.jl
  src/computational_graph/graphvector.jl
  src/computational_graph/io.jl
  src/computational_graph/optimize.jl
  src/computational_graph/transform.jl
  src/computational_graph/tree_properties.jl
  src/frontend/GV.jl
  src/frontend/GV_diagrams/readfile.jl
  src/frontend/frontends.jl
  src/frontend/parquet.jl
  test/compiler.jl
  test/computational_graph.jl
  test/deprecated.jl
Labels: bug, documentation, enhancement

#134 Bugfix
  src/FeynmanDiagram.jl
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/feynmangraph.jl
  src/computational_graph/io.jl
  src/frontend/GV_diagrams/readfile.jl
Labels: bug

#135 Computgraph daniel
  src/computational_graph/optimize.jl
  src/frontend/GV.jl
Labels: bug

#137 Computgraph pr
  src/FeynmanDiagram.jl
  src/backend/compiler.jl
  src/backend/static.jl
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/abstractgraph.jl
  src/computational_graph/constant.jl
  src/computational_graph/feynmangraph.jl
  src/computational_graph/graph.jl
  src/computational_graph/graphvector.jl
  src/computational_graph/io.jl
  src/computational_graph/operation.jl
  src/computational_graph/optimize.jl
  src/computational_graph/transform.jl
  src/computational_graph/tree_properties.jl
  src/frontend/GV.jl
  src/frontend/GV_diagrams/readfile.jl
  src/frontend/frontends.jl
  src/frontend/parquet.jl
  test/compiler.jl
  test/computational_graph.jl
  test/deprecated.jl
Labels: enhancement

#138 Computgraph pr
  src/FeynmanDiagram.jl
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/abstractgraph.jl
  src/computational_graph/eval.jl
  src/computational_graph/optimize.jl
  src/computational_graph/transform.jl
  src/computational_graph/tree_properties.jl
  src/frontend/GV.jl
  test/computational_graph.jl
Labels: enhancement

#139 Tao ad
  src/computational_graph/eval.jl
  src/computational_graph/graph.jl
  src/computational_graph/operation.jl
  src/computational_graph/tree_properties.jl
  test/computational_graph.jl
Labels: enhancement
