Repository numericalEFT/FeynmanDiagram.jl, pull requests merged in 2023-11, with the labels that each got.

#154 API clean up
  example/taylor_expansion.jl
  src/computational_graph/tree_properties.jl
  src/frontend/diagtree.jl
  src/utility.jl
  test/diagram_tree.jl
  test/taylor.jl
Labels: enhancement

#155 Refactor taylor expansion
  example/benchmark.jl
  src/FeynmanDiagram.jl
  src/computational_graph/eval.jl
  src/diagram_tree/DiagTree.jl
  src/utility.jl
  test/taylor.jl
Labels: enhancement

#156 Update FrontEnds API and Bugfix
  src/computational_graph/feynmangraph.jl
  src/computational_graph/optimize.jl
  src/frontend/GV.jl
  src/frontend/GV_diagrams/readfile.jl
  src/frontend/LabelProduct.jl
  src/frontend/pool.jl
  src/utility.jl
  test/front_end.jl
  test/taylor.jl
Labels: bug, documentation, refactor

#157 Add from_taylorcoeff_map
  example/benchmark.jl
  example/taylor_expansion.jl
  src/computational_graph/tree_properties.jl
  src/diagram_tree/tree.jl
  src/utility.jl
  test/taylor.jl
Labels: enhancement

#159 Update optimize, Compilers, and GV
  .github/workflows/CI.yml
  src/backend/static.jl
  src/computational_graph/optimize.jl
  src/frontend/GV.jl
  src/frontend/GV_diagrams/readfile.jl
  test/compiler.jl
  test/computational_graph.jl
  test/taylor.jl
Labels: enhancement, refactor
