Repository numericalEFT/FeynmanDiagram.jl, pull requests merged in 2023-10, with the labels that each got.

#143 Add Power{N} operator in computational graph
  src/backend/static.jl
  src/computational_graph/abstractgraph.jl
  src/computational_graph/eval.jl
  src/computational_graph/feynmangraph.jl
  src/computational_graph/graph.jl
  src/computational_graph/operation.jl
  src/computational_graph/optimize.jl
  test/computational_graph.jl
Labels: enhancement

#145 bugfix in compile and add merge_multi_product
  src/FeynmanDiagram.jl
  src/backend/static.jl
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/optimize.jl
  src/computational_graph/transform.jl
  test/computational_graph.jl
Labels: bug, enhancement

#142 Add Taylor Series
  example/taylor_expansion.jl
  src/FeynmanDiagram.jl
  src/TaylorSeries/TaylorSeries.jl
  src/TaylorSeries/arithmetic.jl
  src/TaylorSeries/constructors.jl
  src/TaylorSeries/parameter.jl
  src/TaylorSeries/print.jl
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/abstractgraph.jl
  src/computational_graph/graph.jl
  src/computational_graph/operation.jl
  src/computational_graph/tree_properties.jl
  src/utility.jl
  test/computational_graph.jl
  test/runtests.jl
  test/taylor.jl
Labels: enhancement

#150 add flatten_chains and the relevant tests
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/optimize.jl
  src/computational_graph/transform.jl
  test/computational_graph.jl
Labels: bug, enhancement

#148 Update AbstractGraph interface
  src/FeynmanDiagram.jl
  src/backend/compiler.jl
  src/backend/static.jl
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/abstractgraph.jl
  src/computational_graph/conversions.jl
  src/computational_graph/feynmangraph.jl
  src/computational_graph/graph.jl
  src/computational_graph/io.jl
  src/computational_graph/optimize.jl
  src/computational_graph/transform.jl
  src/computational_graph/tree_properties.jl
  test/computational_graph.jl
Labels: enhancement, refactor

#152 Bugfix & cleanup exports
  src/FeynmanDiagram.jl
  src/backend/static.jl
  test/taylor.jl
Labels: bug

#151 Tao ad
  example/taylor_expansion.jl
  src/TaylorSeries/TaylorSeries.jl
  src/TaylorSeries/arithmetic.jl
  src/TaylorSeries/constructors.jl
  src/TaylorSeries/parameter.jl
  src/TaylorSeries/print.jl
  src/utility.jl
  test/taylor.jl
Labels: enhancement

#153 add a DiagTree to Graph transformation
  src/FeynmanDiagram.jl
  src/frontend/diagtree.jl
  src/frontend/frontends.jl
Labels: enhancement
