Repository numericalEFT/FeynmanDiagram.jl, pull requests merged in 2023-12, with the labels that each got.

#162 Add properties in Graph
  src/computational_graph/graph.jl
  src/utility.jl
  test/taylor.jl
Labels: enhancement

#164 Update parquet+AD diagram generator in front end
  example/parquet.jl
  example/tree.jl
  src/FeynmanDiagram.jl
  src/TaylorSeries/arithmetic.jl
  src/TaylorSeries/parameter.jl
  src/common.jl
  src/common_new.jl
  src/computational_graph/abstractgraph.jl
  src/computational_graph/graph.jl
  src/expression_tree/build.jl
  src/frontend/GV.jl
  src/frontend/frontends.jl
  src/utility.jl
  test/benchmark.jl
  test/diagram_tree.jl
  test/hubbard.jl
  test/parquet_builder.jl
  test/taylor.jl
Labels: enhancement, refactor

#168 Add transformation/optimization to remove zero-valued subgraphs
  src/FeynmanDiagram.jl
  src/backend/to_dot.jl
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/abstractgraph.jl
  src/computational_graph/optimize.jl
  src/computational_graph/transform.jl
  src/computational_graph/tree_properties.jl
  test/computational_graph.jl
Labels: enhancement

#170 Add open_parenthesis and flatten_prod
  src/FeynmanDiagram.jl
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/transform.jl
Labels: enhancement

#171 Add flatten_sum and refactor all new transform functions
  src/FeynmanDiagram.jl
  src/computational_graph/ComputationalGraph.jl
  src/computational_graph/eval.jl
  src/computational_graph/transform.jl
Labels: documentation, enhancement
